version: '3.1'

services:

  mongo:
    image: mongo:4.4.6
    restart: always
    volumes:
      - ./data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8083:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
      ME_CONFIG_BASICAUTH: false


  it_storm:
    build: .
#    container_name: home_decor
    ports:
      - '3031:3000'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
      ME_CONFIG_BASICAUTH: false
    restart: always

  nginx:
    image: nginx:latest
    volumes:
      - /home/user/it_storm_be/nginx/nginx.conf:/etc/nginx/nginx.conf
      #      поменять!!!
      - /home/user/lls/certs:/etc/nginx/certs
      - static_volume:/static
      - /home/user/it_storm_be/uploads:/uploads
    ports:
      - "3055:3055"
    networks:
      - home_decor-network
    depends_on:
      - home_decor

volumes:
  static_volume:

networks:
  it_storm-network: